name: Update Version

on:
  push:
    branches:
      - production

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract max version from branch names
        run: |
          VERSION=$(git branch -r | grep "version/v" | sed 's/.*version\/v//g' | sort -V | tail -1)
          echo "MAX_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update .version file
        run: |
          MAX_VERSION=$(echo $MAX_VERSION | sed 's/v//g') # remove v prefix
          if [ -f .version ]; then
            CURRENT_VERSION=$(cat .version)
            BASE_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $1"."$2}')
            SUB_VERSION=$(echo $CURRENT_VERSION | awk -F. '{print $3}')

            if [ "$BASE_VERSION" == "$MAX_VERSION" ]; then
              SUB_VERSION=$(printf "%03d" $((SUB_VERSION+1)))
            else
              BASE_VERSION=$MAX_VERSION
              SUB_VERSION=001
            fi
          else
            BASE_VERSION=$MAX_VERSION
            SUB_VERSION=001
          fi
          echo "$BASE_VERSION.$SUB_VERSION" > .version

      - name: Setup GitHub CLI
        run: |
          sudo apt-get install -y gh
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Commit and create a PR if there are changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .version
          git commit -m "Update .version file" || echo "No changes to commit"

          if [ "$(git log -1 --pretty=%B)" == "Update .version file" ]; then
            git checkout -b version-update-branch
            git push origin version-update-branch

            # Create PR using gh cli
            gh pr create --base production --head version-update-branch --title "Update .version file" --body "Automated version bump" --repo $GITHUB_REPOSITORY --label "automated-pr" --reviewer "your_github_username"
          fi

